version: "3"
services: 
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password@12345
      MYSQL_DATABASE: employees_db
    restart: always
  backend:
    container_name: backend_app
    build: ./backend
    ports: 
      - 8000:8000
    restart: always  
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password@12345
      MYSQL_PORT: 3306  
    depends_on: 
      - db
  frontend:
    build: ./FrontEnd
    ports:
      - "5000:5000"
    depends_on:
     - backend
    restart: on-failure     


