apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
    app.kubernetes.io/name: node-backend
  name: backend-deployment
  namespace: node-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      tier: node-backend
  template:
    metadata:
      labels:
        app: my-app
        tier: node-backend
    spec:
      containers:
        - image: nadeem90/backend:latest
          resources:
            requests:
              cpu: 500m
              memory: 600Mi
          name: node-app-backend
          ports:
            - containerPort: 5000
          # env:
          # - name: backend
          #   value: backend:8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-backend
  name: backend
  namespace: node-app-dev
spec:
  selector:
    app: my-app
    tier: node-backend
  ports:
   -  protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer    