apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
    app.kubernetes.io/name: mysql
  name: mysql-deployment
  namespace: node-app
spec:
  selector:
    matchLabels:
      app: my-app
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-app
        tier: mysql
    spec:
      containers:
      - image: nadeem90/mysql:latest
        resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
        name: mysql-db
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql-db
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app.kubernetes.io/name: mysql
  namespace: node-app  
spec:
  selector:
    app: my-app
    tier: mysql
  ports:
   -  protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer    
  